# Generated by Django 4.2.4 on 2023-08-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planetarium_service",
            "0002_alter_reservation_options_alter_showsession_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(
                blank=True, to="planetarium_service.showtheme"
            ),
        ),
    ]
