# Generated by Django 4.2.4 on 2023-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium_service", "0003_alter_astronomyshow_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="shows", to="planetarium_service.showtheme"
            ),
        ),
    ]
